---
- name: USERINIT
  hosts: all
  become: false
  vars:
    username: "nbw"

  tasks:
    - name: packages
      yum:
        name: libselinux-python
        state: latest

    - name: User
      user:
        name: "{{ username }}"
        password: "{{ password|default('$6$Y.LDrxWV$auqKxSczZHRpT//DpZ2PAEi7G7gWodmmQJCj7WS060REkqRzSN.Lxn5cENZl7lsGuCquX9TgqVj/JrXQ75HS2/') }}"
        groups: wheel
        append: true

    - name: Key
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}"

    - name: SUDO_1
      lineinfile:
        path: "/etc/sudoers"
        regexp: '^(Defaults\s+always_set_home)'
        line: '# \1'
        backrefs: true

    - name: SUDO_2
      lineinfile:
        path: "/etc/sudoers"
        regexp: '(%wheel\s+ALL=\(ALL\)\s+ALL)'
        line: '# \1'
        backrefs: true

    - name: SUDO_3
      lineinfile:
        path: "/etc/sudoers"
        regexp: '#.*(%wheel\s+ALL=\(ALL\)\s+NOPASSWD: ALL)'
        line: '\1'
        backrefs: true
...
